### ISSUE TITLE
The latest version of HLDS 9907 is not compatible with the latest version of Rehlds

### ISSUE THREAD

**Issue by all85100** [dreamstalker/rehlds#1020]
The latest version of HLDS 9907 is not compatible with the latest version of Rehlds

error message：/usr/local/games/Half-Life_9907/container/engine_i486.so: undefined symbol: SteamGameServer

**Comment by Atmosuu** [comment]
same problem

**Comment by Moshikot3** [comment]
same

**Comment by Atmosuu** [comment]
I used the steamcmd command and I still get this version Exe build: 23:25:09 Dec  9 2023 (9907), should I change the launch parameter?

**Comment by anzz1** [comment]
I just tested this on a fresh VM of Debian 10 (Buster), with the non-free repository enabled in /etc/apt/sources.list and no other modifications.

```cmd
uname -a
> Linux buster 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

dpkg --add-architecture i386
apt-get install steamcmd
/usr/games/steamcmd

login anonymous
app_update 90 -beta steam_legacy validate
> Error! App '90' state is 0xE after update job.
app_update 90 -beta steam_legacy validate
> Success! App '90' fully installed.
exit

cd /root/.steam/SteamApps/common/Half-Life
./hlds_run -console -game cstrike

version
> Protocol version 48
> Exe version 1.1.2.7/Stdio (cstrike)
> Exe build: 19:52:19 Aug  3 2020 (8684)
```

So there must be something wrong with your installation. Also due to the fact that `steamcmd` is distributed via package managers in various Linux distros, there are probably bugs and differences between versions. Package managers are notorious for this.

The [Windows version](https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip) on the other hand is same for everyone, and works fine. Sometimes it has bugs too though when downloading things, that's why the `validate` option is recommended.

steamcmd can be finicky. This is exactly why I gave the link to the pre-downloaded archive in my above comment, along with the comment "in case steamcmd is giving you any trouble" :slightly_smiling_face:

**Comment by anzz1** [comment]
For even easier installation, it's possible to get archives of HLDS with ReHLDS preinstalled along with the default plugins MetaMod, AMX Mod X, etc. from the ReHLDS.ru site: https://rehlds.ru/index.php?id=rehlds_game_server

**Comment by Atmosuu** [comment]
> Alternatively the (clean) files for 8684 are archived here, in case steamcmd is giving you any trouble: Linux: https://dl.rehlds.ru/hlds/hlds_linux_8684.zip

gg by link 

Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 19:52:19 Aug  3 2020 (8684)

**Comment by all85100** [comment]
Can't the official develop a new version that is compatible with hlds 9907 ？

**Comment by carl07chia** [comment]
I second the motion, How hard would it be to make a new release with the new Engine Compatibility.
