### ISSUE TITLE
Mod_LoadLeafs: oversized loadmodel

### ISSUE THREAD

**Issue by krangm** [dreamstalker/rehlds#332]
hello

since version 3.0.0.402 map (kz_2001) crashing server with this fatal error
http://i.imgur.com/K4nqMe8.png
versions ≤ 3.0.0.400 are ok with this map
i've tested only bugfixed dlls (not pure)

thanks!

**Comment by WPMGPRoSToTeMa** [comment]
[This commit](https://github.com/dreamstalker/rehlds/commit/f6ce3a447c10981b01d34438a0452ebd820408c8) breaks it. So, I think `Mod_DecompressVis` is never called in multiplayer, because gPVS always is not `nullptr` [here](https://github.com/dreamstalker/rehlds/blob/47964c847bed3ee8fee78b01b4798022c0c8205a/rehlds/engine/cmodel.cpp#L72-L75) since [`gPVS` is set in `CM_CalcPAS`](https://github.com/dreamstalker/rehlds/blob/47964c847bed3ee8fee78b01b4798022c0c8205a/rehlds/engine/cmodel.cpp#L168) which [is called from `SV_SpawnServer`](https://github.com/dreamstalker/rehlds/blob/6715402425e2247818086a51f9662c0605447177/rehlds/engine/sv_main.cpp#L6089-L6099).

**Comment by krangm** [comment]
well, the question is will it be fixed in future versions?
or how can i detect maps which i should avoid to prevent server crash? (worse scenario)

**Comment by In-line** [comment]
@WPMGPRoSToTeMa So. As I understood server didn't check model->numleafs in multiplayer and worked fine. Can we transform that to warning ? (Con_Printf("Warning: ....") )

**Comment by In-line** [comment]
@WPMGPRoSToTeMa So. Do you think we need to change it to Con_Printf("Warning: ...") ? As I understood that kind of check is necessary anyway.

**Comment by WPMGPRoSToTeMa** [comment]
@In-line nope, I think multiplayer server can eat this leaf count without problems, we need to learn how PVS works on server.

**Comment by LevShisterov** [comment]
Closed via #336
