### ISSUE TITLE
Got a few questions

### ISSUE THREAD

**Issue by di57inct** [dreamstalker/rehlds#514]
1. I'm still using HLDS build 6153 with ReHLDS build 1159. Which version of ReHLDS is the last one designed to patch that original HLDS build and should I update it? I'm asking because I haven't had any problems so far with the server and don't plan on having any either.

2. Are there any known and unfixed issues with the latest HLDS builds and/or ReHLDS builds for it and should I fully upgrade to them? Would they require a new MetaMod and AmxModX version update as well?

Thank you for this awesome project and keeping GoldSource games alive. You guys are awesome.

**Comment by voed** [comment]
All requirements you can find in readme

**Comment by simeonniko** [comment]
Pay attention to https://github.com/theAsmodai/metamod-r 
and https://github.com/alliedmodders/amxmodx/pull/417

**Comment by In-line** [comment]
1. It is really difficult to say, because every change in ReHLDS can break something. I think you should review community feedback for new versions before updating, although I recommend you to update whenever possible.
2․ There are many unfixed bugs in HLDS, that are fixed in ReHLDS. You should use AMX Mod X 1.8.3 last dev version or 1.8.2 (seems to work without cstrike module)

**Comment by In-line** [comment]
Closing as non active.
