### ISSUE TITLE
Adding WHBlock from s1lentq

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#690]
https://github.com/s1lentq/ReGameDLL_CS/issues/350
It would be nice to have this configurable from rehlds.

**Comment by krangm** [comment]
WHB is not even working properly on some gamemodes e.g. `ag`
dont even think to add this to ReHLDS

i reported about bugs in the original thread at aghl.ru since year ago several times
yet no reply from author or any fixes

but ofc if goldsrc for you is only cs... then whatever

**Comment by hashnimmo** [comment]
I personally don't agree with this suggestion. It's nice to have it separately as it is now, other than having it on ReHLDS or ReGameDLL. Because these 2 projects doesn't focus on interfering with the original functionality of HLDS, rather it focus on performance improvements.

WHBlocker plugin is a great server-side anti cheat solution for wall hacks and I have it installed in my server, from that I have managed to block most of the wall and aim bot hackers and they have no clue how to get their hacks working again. In fact that's the only anti-cheat plugin I have installed and I find it pretty neat.

But that doesn't make it qualified to be in any of the above 2 projects. Not to mention that it also add more load on the host server so I don't know how that's gonna make ReHLDS any better than original HLDS.

**Comment by hashnimmo** [comment]
I personally don't agree with this suggestion. It's nice to have it separately as it is now, other than having it on ReHLDS or ReGameDLL. Because these 2 projects doesn't focus on interfering with the original functionality of HLDS, rather it focus on performance improvements.

WHBlocker plugin is a great server-side anti cheat solution for wall hacks and I have it installed in my server, from that I have managed to block most of the wall and aim bot hackers and they have no clue how to get their hacks working again. In fact that's the only anti-cheat plugin I have installed and I find it pretty neat.

But that doesn't make it qualified to be in any of the above 2 projects. Not to mention that it also add more load on the host server so I don't know how that's gonna make ReHLDS any better than original HLDS.
