### ISSUE TITLE
ReHLDS with new HLDS version?

### ISSUE THREAD

**Issue by WhiteFang1319** [dreamstalker/rehlds#706]
Since CS 1.6 is officially getting updates now and I think HLDS is also getting. Is it possible to use ReHLDS with the new HLDS version? I know ReHLDS is for 6153 version but still asking because it's getting some new good features

**Comment by Mistrick** [comment]
ReHLDS based on 6153 version of HLDS and completely replace HLDS. You got nothing new after install ReHLDS over new HLDS.
You can only wait until someone backport new feautures to ReHLDS. As I know new builds got only security fixes which already fixed in ReHLDS. Mostly fixes and features got clientside and gamedll.
