### ISSUE TITLE
[SUGGESTION] When a large number of entities emit sounds, sounds get cut for players who hear them.

### ISSUE THREAD

**Issue by hellmoss** [dreamstalker/rehlds#773]
https://youtu.be/rdXzFTY5bs4
This must be a shortcoming of the GoldSource engine but is there anything that can be done through REHLDS?
I know making the entity emit sounds less frequently or reducing sound emitting in general will help. Not really an urgent issue.
This is just an example, I've noticed this "problem" on servers without any special entities but just from players emitting many sounds.

**Comment by NukemD** [comment]
It's an engine limit on the client side, the server can't do anything about it.

https://github.com/ValveSoftware/halflife/blob/master/dlls/soundent.h

The maximum number of sounds in the world is 64, and I assume that a number of them are reserved for specific functions, making the usable value less. Once the sound list overflows, the new sounds will not play, which is why nihilanth's voice was cut off mid-sentence; because the next word in the sentence was overflowed out.

You have to remember that Half-Life is a 90s game and has a 90s sound engine inherited from an older Quake engine. Sound cards of the era couldn't handle huge numbers of sounds playing at once. You have to remember that PCM audio on sound cards was still a relatively new thing in the mid 90s, the DOS era that gaming was moving away from was almost entirely reliant on FM synthesis with very limited PCM audio 

At least two mods got around the limited sound engine by partially or fully replacing it with FMOD. Natural Selection used it for ambient music and Sven Coop entirely replaces the old sound system with FMOD.

**Comment by hellmoss** [comment]
That was pretty enlightening, thanks!
