### ISSUE TITLE
sys_ticrate > 1000

### ISSUE THREAD

**Issue by Maxpain177** [dreamstalker/rehlds#90]
Why rehlds not supports server fps > 1000?
When i set sys_ticrate to 1060 (for example), in stats fps still < 1000 (unstable, 850-990)

Intel Xeon E5-1620 v2, Ubuntu 14.04 with kernel 4.1.0-rt10 (realtime, 1000hz).

**Comment by theAsmodai** [comment]
Running with more than 1000 fps doesn't make sense. It's better to have a more stable value.
Maybe I'll try to do something for fps stabilization.

**Comment by WPMGPRoSToTeMa** [comment]
100-250 fps is enough. I don't know why you want 1000 fps and more.

**Comment by deliriumbg** [comment]
Stabilizing the FPS would be a great improvement. 
mmtimer did that but for the expense of high CPU usage..

**Comment by johnally** [comment]
If I'm not mistaken running your server at higher fps makes your server response faster (it can be a good or bad thing). For instance, if I run my server at 1000fps, there's a drop in latency compared to if my server was run at 100-125fps. One concern though, is that running at such high fps involves stability issue and cpu usage concern.

**Comment by johnstt** [comment]
Do you guys have any ideas about why server FPS *isn't* stable on machines with tons of spare CPU time?

I haven't tried reHLDS myself, but does it address this at all? Can I expect higher server fps than with the official release of HLDS?

If you want to see why 100 fps isn't enough, take the sdk code for grenades or rockets or something and make them think every 1ms instead of every 100ms. Lots of stuff can be smoothed out and made more responsive with higher framerates.

**Comment by txdv** [comment]
Having a server ticrate of 1000 doesn't add much value if you don't increase the update rate to the client 10 fold as well, which increases the traffic usage significantly. This mystic 1000 server fps is rather useless, 100 is plenty enough.

**Comment by theAsmodai** [comment]
FPS instability caused by inaccuracy of the system timer. This is necessary for efficient CPU resource consumption.

**Comment by Maxpain177** [comment]
Thanks. On ReHLDS build 795 you fixed sys_ticrate problem. Now my server fps can increase more then 1000.
