### ISSUE TITLE
Increase `sv_zmax` default value

### ISSUE THREAD

**Issue by RauliTop** [dreamstalker/rehlds#920]
Default value seems to be low.
https://github.com/dreamstalker/rehlds/blob/22a00eff892c9bee807773120818dc2337f632e8/rehlds/engine/sv_main.cpp#L130

An example on cs_assault (official map):
https://imgur.com/lv7Dvie

The question now is, what will be a better value?

**Comment by etojuice** [comment]
On cs_assault maximum visible distance was set by the mapper to 4620. Anyways, the default value is kinda low yeah.

**Comment by StevenKal** [comment]
A lot of maps have a custom value defined by mapper, but usually not enough (like for "cs_assault" where this is ugly to see the front disappears).
Because GameDLL allows to set a custom value via a KeyValue ("MaxRange" to the entity "worldspawn", which alters the EntVars's "speed" member & the game set this CVar to the value).
A fullly reliable solution/fix, is to just put your custom high value (like "20000") in "amx.cfg" to solve it well for all maps.

**Comment by UnrealKaraulov** [comment]
Yes, this limit is useless. Need possible to remove it for all maps.

**Comment by wopox1337** [comment]
Problems with the map, not the game engine.
