### ISSUE TITLE
SV_BuildSoundMsg: forgoten newline `\n` in `Con_Printf()`

### ISSUE THREAD

**Issue by wopox1337** [dreamstalker/rehlds#965]
https://github.com/dreamstalker/rehlds/blob/5e8b0ba616c571646c4fc67b188d1a630650d928/rehlds/engine/sv_main.cpp#L683-L698

as example below:
https://github.com/dreamstalker/rehlds/blob/5e8b0ba616c571646c4fc67b188d1a630650d928/rehlds/engine/sv_main.cpp#L724

**Comment by StevenKal** [comment]
Knowing you have repository rights as collaborator & build releases too like the owner, can you explain why you do not just directly add your changes instead of creating issues or PRs, especially for tiny things like this?
Same thing happen in ReGame like [here](https://github.com/s1lentq/ReGameDLL_CS/pull/827).
